# Generated by Django 5.0.6 on 2024-06-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAsistencia', '0006_alter_empleado_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
