# Generated by Django 5.0.6 on 2024-06-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAsistencia', '0008_empleado_fecha_registro_empleado_hora_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='genero',
        ),
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(default=1036964850, max_length=50),
            preserve_default=False,
        ),
    ]
