# Generated by Django 5.0.6 on 2024-06-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAsistencia', '0010_empleado_hora_marcacion_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('hora_marcacion_real', models.CharField(max_length=8)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlAsistencia.empleado')),
            ],
        ),
    ]
