# Generated by Django 5.0.6 on 2024-07-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAsistencia', '0012_alter_empleado_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(default='operario', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='centro_de_costos',
            field=models.CharField(default='I520', max_length=100),
            preserve_default=False,
        ),
    ]
